### ISSUE TITLE
Repeated ga4gh in import statements

### ISSUE THREAD

**Issue by david4096** [dcolligan/ga4gh-schemas#7]
It would be nice if the namespace didn't repeat in the nesting.

I currently enter `from ga4gh.schemas.ga4gh import metadata_pb2 as metadata` but would prefer `from ga4gh.schemas import metadata_pb2 as metadata`.

**Comment by dcolligan** [comment]
If we want that, we should change the structure of how the `proto` files in the schemas repo are organized.

**Comment by david4096** [comment]
If that works with the package name statements and doesn't cause any huge headaches in compliance, it might be a good idea.

**Comment by dcolligan** [comment]
Moved to https://github.com/dcolligan/ga4gh-schemas/issues/7

Closing...
